Add points.
mfd-engine-team/robloxlabs.com pull request #2
Opened 2021-03-13 01:43 UTC by GithubPagesStuff

2021-03-13 01:45 UTC, rbx-nsg commented
You put this in the wrong directory

2021-03-13 01:56 UTC, GithubPagesStuff commented
There.

2021-03-13 03:03 UTC, rbx-nsg commented
There are many issues with this

2021-03-13 03:24 UTC, rbx-nsg requested changes

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/__pageIndex.ts
> +	Description: Load Place info script
You wrote this, I didn't, add your name, also change the FileName and description to suit this controller

2021-03-13 03:24 UTC, rbx-nsg commented on .gitignore
> +Lib/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/all-time.d.ts #fix a weird bug
Remove this

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/__pageIndex.ts
> +var fs = require('fs')
DO NOT USE REQUIRE UNLESS THE RESPONSE IS VOLATILE!!
Use:
```ts
import filestream from 'fs';
```

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/__pageIndex.ts
> +/*
This file shouldn't be called __PageIndex.ts, you can drop this and move to _P-userId.ts

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/__pageIndex.ts
> +import { _dirname } from '../../../../../../../../Roblox/Helpers/Constants/Directories';
Do not use this as it's implemented into Roblox.Api

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/__pageIndex.ts
> +	func: async (_req, res) => {
import Request and Response from express-serve-static-core and make this function into:
```ts
func: (request: Request, response: Response) => { ... }
```

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/__pageIndex.ts
> +/*
Implementation Notes:
This should use an ApiClient from 'http//points.api.sitetest4.robloxlabs.com/'

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/__pageIndex.ts
> +		}
It should respond with a 405 when the method is incorrect

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/__pageIndex.ts
> +    },
All of this "try catch" code is volatile, please fix, look at a different controller, such as an AbTesting controller for an example

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/all-time.ts
>  	***
Follow the same issues for the previous file

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Helpers/WebHelpers/Points/Get.ts
> +import fs from 'fs';
These helpers aren't reliable, and they don't take a namespace or class, fix them

2021-03-13 03:24 UTC, rbx-nsg commented on Roblox/Helpers/WebHelpers/Points/Set.ts
> +import fs from 'fs';
These helpers aren't reliable, and they don't take a namespace or class, fix them

2021-03-13 18:52 UTC, rbx-nsg requested changes

2021-03-13 18:52 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/_P-userId.ts
>  /*
Look at the way you have _P-userId/_P-userId here, move back change the path from Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/_P-userId.ts to Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId.ts

2021-03-13 18:52 UTC, rbx-nsg commented on Roblox/Controllers/Roblox.Points/v1/universes/_P-universeId/users/_P-userId/_P-userId.ts
> +import { _dirname } from '../../../../../../../Helpers/Constants/Directories';
Wrong module, and a really cursed path

2021-03-15 22:12 UTC, rbx-nsg commented
Umm, you're going to have to put that onto a different pull request, because it will conflict with this source code

2021-03-15 22:13 UTC, GithubPagesStuff commented
ok.

2021-03-15 22:13 UTC, closed without merging

2021-03-15 22:14 UTC, rbx-nsg commented
Wait for me to push the latest changes before making the new pull request so you can pull it into your repo