Add EphemeralCounters
mfd-engine-team/robloxlabs.com pull request #87
Opened 2021-03-31 02:33 UTC by GithubPagesStuff

2021-03-31 02:35 UTC, rbx-nsg commented
Sorry I broke the action

2021-03-31 02:37 UTC, GithubPagesStuff commented
Hopefully now it'll build

2021-03-31 02:38 UTC, rbx-nsg commented
OK This one is my fault also

2021-03-31 02:38 UTC, rbx-nsg commented
![image](https://user-images.githubusercontent.com/79342039/113082555-9c842e00-91d2-11eb-9a10-ec433d6d96e4.png)

2021-03-31 08:12 UTC, rbx-nsg requested changes

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +import { FASTLOGS, FLog, LOGGROUP } from '../../../././../../Helpers/WebHelpers/Roblox.Util/Roblox.Util.FastLog';
These paths are cursed

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +	func: (_req: any, res): void => {
`_req: any` should be changed to `request: Request` (import { Request, Response } from 'express'), and `res` should be `response: Response`

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +        const keys = Object.keys(jsn)
Do body check here, as for the jsn = JSON.parse(bdy), you clearly didn't test this at all, as the body is parsed by default, in the future you will have to manually tell the controller to parse JSON

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +        return res.status(404);
Development artifact, the code below this is unreachable.

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +            FASTLOGS(FLog['EphemeralCounters'], '[FLog::EphemeralCounters] %s', b);
These should be done in the HandleIncrementCounter

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/ApiServices/Roblox.EphemeralCounters.Service/Roblox.EphemeralCounters.Service/EphemeralCountersService.ts
> +		if (!AskIfWeAreAvailable(response)) return;
This shouldn't be here, this is from development, this will be removed from the PointsService also, as will the flag DFFlag::EphemeralCountersServiceEnabled

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/ApiServices/Roblox.EphemeralCounters.Service/Roblox.EphemeralCounters.Service/EphemeralCountersService.ts
> +		return response.status(200).send();
1: Use the actual DataBase instead of the JSON Store.
2: Format your code with prettier!

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/ApiServices/Roblox.EphemeralCounters.Service/Roblox.EphemeralCounters.Service/EphemeralCountersService.ts
> +	}
This is not needed, as the response handling should always be done in the handler

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/ApiServices/Roblox.EphemeralCounters.Service/Roblox.EphemeralCounters.Service/EphemeralCountersService.ts
> +	}
Nor is this neeeded

2021-03-31 08:12 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +	Written By: idk
If you could, it is preferable if you put your real-name or your github username here.

2021-03-31 13:34 UTC, GithubPagesStuff commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +        const keys = Object.keys(jsn)
wait did my code not save

2021-03-31 13:35 UTC, rbx-nsg commented
Please review the rest of the changes requested and update your code accordingly to meet the standards

2021-03-31 15:50 UTC, GithubPagesStuff commented
Changed active branch for working on EphemeralCounters.

2021-03-31 16:04 UTC, rbx-nsg commented
Why does that matter?

2021-03-31 16:04 UTC, rbx-nsg commented
Please keep this pull request

2021-03-31 16:08 UTC, rbx-nsg requested changes

2021-03-31 16:08 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
>          const jsn = JSON.parse(bdy)
You changed basically nothing

2021-03-31 16:08 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +		return response.status(200);
This is even worse than before

2021-03-31 16:08 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/Increment.ts
> +		EphemeralCountersService.HandleIncrementCounter(request.query["counterName"].toString(), parseInt(request.query["amount"].toString()), response)
Bruh

2021-04-01 09:02 UTC, rbx-nsg requested changes

2021-04-01 09:02 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +            const b = bdy[key];
Do some sanitization of Keys here, that's preferable so xss is avoidable

2021-04-01 09:02 UTC, rbx-nsg commented on SQL/counter.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```sql
CREATE SCHEMA IF NOT EXISTS `RobloxAnalytics` ;
CREATE TABLE IF NOT EXISTS `RobloxAnalytics`.`counter` (
  `Id` bigint NOT NULL AUTO_INCREMENT,
  `Name` text NOT NULL,
  `Count` bigint NOT NULL,
    PRIMARY KEY (`Id`),
  UNIQUE KEY `Id_UNIQUE` (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;
```

2021-04-01 09:02 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/Increment.ts
> +		await EphemeralCountersService.HandleIncrementCounter(request.query["counterName"].toString(), parseInt(request.query["amount"].toString()), response) //yeah idk why it's being weird. It was throwi
Still no sanitization

2021-04-01 09:08 UTC, rbx-nsg commented on Assemblies/ApiServices/Roblox.EphemeralCounters.Service/Roblox.EphemeralCounters.Service/EphemeralCountersService.ts
> +		return response.status(result).send();
Sorry, if the response status is 500, then the body should be:
```json
{
  "Message": "An error has occurred."
}
```

2021-04-01 15:47 UTC, rbx-nsg requested changes

2021-04-01 15:47 UTC, rbx-nsg commented on Assemblies/ApiServices/Roblox.EphemeralCounters.Service/Roblox.EphemeralCounters.Service/EphemeralCountersService.ts
>  		// Just make this do nothing for the time being; aka. echo back the user and universe, with an alltimescore of 0
Remove this comment, and the other one

2021-04-01 15:47 UTC, rbx-nsg commented on Assemblies/Data/Counters/Roblox.Data.Counters/Counter.ts
> +	public Count: Number;
The type of this should be `number`, and not `Number`

2021-04-01 15:47 UTC, rbx-nsg commented on Assemblies/Data/Counters/Roblox.Data.Counters/Counter.ts
> +}
Move this to Assemblies/Util/SanitizeData.ts
```ts
export function SanitizeData(data: string) {
    return data.replace(/[^a-z0-9+]+/gi, '');
}
```

2021-04-01 15:47 UTC, rbx-nsg commented on Assemblies/Data/Counters/Roblox.Data.Counters/Counter.ts
> +		}
Move this entire thing to a helper in Roblox.Data.Counters (CreateOrIncrementCounter(Name: string, Amount: number))

2021-04-01 15:47 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +import { EphemeralCountersService } from '../../../././../../ApiServices/Roblox.EphemeralCounters.Service/Roblox.EphemeralCounters.Service/EphemeralCountersService'
Another cursed import

2021-04-01 15:47 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +import { FASTLOGS, FLog, LOGGROUP } from '../../../././../../Helpers/WebHelpers/Roblox.Util/Roblox.Util.FastLog';
Damn cursed imports

2021-04-01 15:47 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
> +            EphemeralCountersService.HandleIncrementCounterNoResp(a,b)
```ts
await EphemeralCountersService.HandleIncrementCounterNoResp(a,b)
```

2021-04-01 15:47 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/Increment.ts
> +import { EphemeralCountersService } from '../../../././../../ApiServices/Roblox.EphemeralCounters.Service/Roblox.EphemeralCounters.Service/EphemeralCountersService'
Why are the paths so cursed, I am talking about the `../././../` part

2021-04-01 16:46 UTC, rbx-nsg approved these changes

2021-04-01 16:46 UTC, rbx-nsg commented on Assemblies/ApiServices/Roblox.EphemeralCounters.Service/Roblox.EphemeralCounters.Service/EphemeralCountersService.ts
> +}
Changed this on my branch, pretty similar to yours, only some changes to file names

2021-04-01 16:46 UTC, rbx-nsg commented on Assemblies/Data/Counters/Roblox.Data.Counters/Counter.ts
> +}
Cleaned this up

2021-04-01 16:46 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/BatchIncrement.ts
>  	},
Fixed this by using the new ServiceMethods

2021-04-01 16:46 UTC, rbx-nsg commented on Assemblies/Services/Roblox.EphemeralCounters.Service/Controllers/v1.1/Counters/Increment.ts
> +		);
Updated this by using the IncrementRequest interface

2021-04-01 16:48 UTC, merged